(() => {
  const cfg=window.AZ_STORE,api=`${cfg.supabaseUrl}/rest/v1`,authUrl=`${cfg.supabaseUrl}/auth/v1`;
  let token=sessionStorage.getItem("az-admin-token")||"";
  const H=(extra={})=>({apikey:cfg.anonKey,Authorization:`Bearer ${token||cfg.anonKey}`,"Content-Type":"application/json",...extra});
  const call=async(path,options={})=>{const r=await fetch(`${api}/${path}`,{...options,headers:H(options.headers)});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null};
  const money=n=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n||0);
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
  const orderLabels={pending_payment:"Pago pendiente",payment_submitted:"Comprobante recibido",payment_confirmed:"Pago confirmado",in_preparation:"En preparación",completed:"Completado",cancelled:"Cancelado"};
  const msg=(id,text,type="")=>{const el=document.querySelector(id);if(el){el.textContent=text;el.className=`form-status ${type}`}};
  const split=v=>v.split(",").map(x=>x.trim()).filter(Boolean);
  const panel=document.querySelector("#admin-panel"),login=document.querySelector("#admin-login");

  async function check(){if(!token)return false;try{const me=await call("admin_users?select=user_id");if(!me.length)throw new Error("Sin permisos");login.hidden=true;panel.hidden=false;await Promise.all([loadCategories(),loadProducts(),loadOrders(),loadSettings()]);return true}catch{token="";sessionStorage.removeItem("az-admin-token");return false}}
  document.querySelector("#login-form").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));msg("#login-status","Verificando…");try{const r=await fetch(`${authUrl}/token?grant_type=password`,{method:"POST",headers:{apikey:cfg.anonKey,"Content-Type":"application/json"},body:JSON.stringify(d)});if(!r.ok)throw new Error(await r.text());const session=await r.json();token=session.access_token;sessionStorage.setItem("az-admin-token",token);if(!await check())throw new Error("Esta cuenta no está autorizada como administradora.");}catch(error){msg("#login-status","No fue posible ingresar. Verifica la cuenta y sus permisos.","error");console.error(error)}};
  document.querySelector("#logout").onclick=()=>{sessionStorage.removeItem("az-admin-token");location.reload()};
  document.querySelectorAll("[data-admin-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-admin-tab]").forEach(x=>x.classList.toggle("is-active",x===b));document.querySelectorAll("[data-admin-panel]").forEach(x=>x.hidden=x.dataset.adminPanel!==b.dataset.adminTab)});

  let categories=[],editingImageUrl="";
  async function loadCategories(){categories=await call("store_categories?select=id,name&order=sort_order");document.querySelector("#admin-category").innerHTML=categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}
  async function loadProducts(){const products=await call("store_products?select=*&order=created_at.desc");const byId=new Map(products.map(product=>[product.id,product]));const el=document.querySelector("#admin-products");el.innerHTML=products.length?products.map(p=>`<article><div>${p.image_url?`<img src="${esc(p.image_url)}" alt="" width="90" height="120">`:""}</div><div><strong>${esc(p.name)}</strong><span>${money(p.price_cop)} · ${p.stock} unidades · ${p.active?"Visible":"Oculto"}</span></div><button data-edit="${p.id}">Editar</button></article>`).join(""):'<p>No hay productos todavía.</p>';el.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>fillProduct(byId.get(b.dataset.edit)))}
  function fillProduct(p={}){const f=document.querySelector("#product-form");editingImageUrl=p.image_url||"";f.reset();["id","name","category_id","description","price_cop","stock"].forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??""});f.elements.sizes.value=(p.sizes||[]).join(", ");f.elements.colors.value=(p.colors||[]).join(", ");f.elements.active.checked=p.active!==false;scrollTo({top:0,behavior:"smooth"})}
  document.querySelector("#cancel-product").onclick=()=>fillProduct();
  document.querySelector("#product-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),id=d.id||crypto.randomUUID();msg("#product-status","Guardando…");try{let imageUrl=null;const file=f.elements.image.files[0];if(file){if(file.size>8*1024*1024)throw new Error("La imagen supera 8 MB");const ext=file.name.split(".").pop().toLowerCase(),path=`${id}/${crypto.randomUUID()}.${ext}`;const up=await fetch(`${cfg.supabaseUrl}/storage/v1/object/product-images/${path}`,{method:"POST",headers:{apikey:cfg.anonKey,Authorization:`Bearer ${token}`,"Content-Type":file.type},body:file});if(!up.ok)throw new Error(await up.text());imageUrl=`${cfg.supabaseUrl}/storage/v1/object/public/product-images/${path}`;}const body={id,name:d.name,slug:`${d.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}-${id.slice(0,6)}`,category_id:d.category_id,description:d.description,price_cop:Number(d.price_cop),stock:Number(d.stock),sizes:split(d.sizes||""),colors:split(d.colors||""),active:f.elements.active.checked,image_url:imageUrl||editingImageUrl||null};await call("store_products",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(body)});fillProduct();await loadProducts();msg("#product-status","Producto guardado.","success");}catch(error){msg("#product-status","No fue posible guardar el producto.","error");console.error(error)}};

  async function loadOrders(){const orders=await call("store_orders?select=*,store_order_items(*)&order=created_at.desc");const el=document.querySelector("#admin-orders");el.innerHTML=orders.length?orders.map(o=>`<article class="admin-order"><header><div><strong>Pedido ${o.id.slice(0,8).toUpperCase()}</strong><span>${new Date(o.created_at).toLocaleString("es-CO")}</span></div><select data-order-status="${o.id}">${Object.entries(orderLabels).map(([value,label])=>`<option value="${value}" ${value===o.status?"selected":""}>${label}</option>`).join("")}</select></header><p>${esc(o.customer_name)} · ${esc(o.customer_whatsapp)} · ${esc(o.city)}</p><ul>${o.store_order_items.map(i=>`<li>${i.quantity} × ${esc(i.product_name)}${i.size?` · ${esc(i.size)}`:""}${i.color?` · ${esc(i.color)}`:""}</li>`).join("")}</ul><strong>${money(o.total_cop)}</strong>${o.payment_proof_path?`<button data-proof="${esc(o.payment_proof_path)}">Ver comprobante</button>`:'<small>Sin comprobante</small>'}</article>`).join(""):'<p>No hay pedidos todavía.</p>';el.querySelectorAll("[data-order-status]").forEach(s=>s.onchange=async()=>{const previous=orders.find(o=>o.id===s.dataset.orderStatus)?.status;try{await call(`store_orders?id=eq.${s.dataset.orderStatus}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:s.value})})}catch(error){s.value=previous;alert("No fue posible actualizar el pedido. Revisa el inventario antes de confirmar el pago.");console.error(error)}});el.querySelectorAll("[data-proof]").forEach(b=>b.onclick=()=>viewProof(b.dataset.proof))}
  async function viewProof(path){const r=await fetch(`${cfg.supabaseUrl}/storage/v1/object/payment-proofs/${path}`,{headers:{apikey:cfg.anonKey,Authorization:`Bearer ${token}`}});if(!r.ok)return alert("No fue posible abrir el comprobante.");const url=URL.createObjectURL(await r.blob());open(url,"_blank","noopener")}
  document.querySelector("#refresh-orders").onclick=loadOrders;
  async function loadSettings(){const s=(await call("store_settings?id=eq.1&select=*"))[0]||{};const f=document.querySelector("#bank-form");["bank_name","account_type","account_number","account_holder","holder_document"].forEach(k=>f.elements[k].value=s[k]||"");f.elements.enabled.checked=!!s.transfers_enabled}
  document.querySelector("#bank-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),required=["bank_name","account_type","account_number","account_holder","holder_document"];if(f.elements.enabled.checked&&required.some(key=>!String(d[key]||"").trim())){msg("#bank-status","Completa todos los datos bancarios antes de habilitar transferencias.","error");return}try{await call("store_settings?id=eq.1",{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({transfers_enabled:f.elements.enabled.checked,bank_name:d.bank_name||null,account_type:d.account_type||null,account_number:d.account_number||null,account_holder:d.account_holder||null,holder_document:d.holder_document||null})});msg("#bank-status","Datos guardados.","success")}catch(error){msg("#bank-status","No fue posible guardar los datos.","error");console.error(error)}};
  check();
})();
