const pieces = [
  {title:'Marfil',src:'assets/novia-encaje.webp',alt:'Vestido de novia satinado de manga larga',description:'Satinado limpio, mangas largas y pliegues diagonales que definen una silueta serena.',details:['Nombre — provisional','Colección — Novias','Lectura — Sastrería y pureza']},
  {title:'Encaje Imperial',src:'assets/novia-satin.webp',alt:'Vestido de novia de manga larga con encaje integral',description:'Escote profundo, encaje floral y una falda amplia que prolonga el detalle hasta la cola.',details:['Nombre — provisional','Colección — Novias','Lectura — Encaje y presencia']},
  {title:'Regencia',src:'assets/novia-sirena.webp',alt:'Vestido de novia de cuello alto y encaje',description:'Cuello alto, manga larga y aplicaciones que equilibran tradición y estructura.',details:['Nombre — provisional','Colección — Novias','Lectura — Clasicismo y detalle']},
  {title:'Aurora',src:'assets/novia-romantica.webp',alt:'Vestido de novia con escote abierto y aplicaciones florales',description:'Un escote abierto enmarcado por flores y una falda luminosa de gran amplitud.',details:['Nombre — provisional','Colección — Novias','Lectura — Romanticismo y volumen']},
  {title:'Azul Medianoche',src:'assets/quince-azul.webp',alt:'Vestido azul medianoche de XV años',description:'Azul profundo, corsetería bordada y destellos que recorren una falda de gran volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Profundidad y brillo']},
  {title:'Verde Salvia',src:'assets/quince-verde.webp',alt:'Vestido verde salvia de XV años',description:'Un verde sereno con aplicaciones florales y transparencias delicadas en el cuerpo.',details:['Nombre — provisional','Colección — XV años','Lectura — Frescura y detalle']},
  {title:'Rosa Nácar',src:'assets/quince-rosa.webp',alt:'Vestido rosa nácar de XV años',description:'Rosa luminoso, cuello bordado y una silueta clásica de presencia suave.',details:['Nombre — provisional','Colección — XV años','Lectura — Romance y luz']},
  {title:'Violeta Imperial',src:'assets/quince-lavanda.webp',alt:'Vestido violeta de XV años',description:'Un violeta sofisticado con cuello transparente y bordados que acentúan el volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Color y textura']},
  {title:'Rosa Corona',src:'assets/quince-rosa-retrato.webp',alt:'Vestido rosa de XV años con modelo y corona',description:'Encaje de manga larga, brillo tenue y una imagen completa de celebración.',details:['Nombre — provisional','Colección — XV años','Lectura — Elegancia ceremonial']},
  {title:'Lirio',src:'assets/comunion-lirio.webp',alt:'Vestido blanco de Primera Comunión con cinturón floral',description:'Mangas delicadas, cinturón satinado y un borde floral que enmarca la falda.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Pureza y detalle']},
  {title:'Gracia',src:'assets/comunion-gracia.webp',alt:'Vestido satinado de Primera Comunión',description:'Satinado limpio, falda plisada y una flor lateral de expresión serena.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Sencillez y luz']},
  {title:'Coral de Luz',src:'assets/comunion-coral.webp',alt:'Vestido blanco de encaje con cinturón coral',description:'Encaje floral y un acento coral que aporta identidad a la silueta clásica.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Encaje y contraste']},
  {title:'Capilla',src:'assets/comunion-capilla.webp',alt:'Vestido blanco de Primera Comunión en una iglesia',description:'Una pieza de encaje suave presentada en la intimidad luminosa de la ceremonia.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Tradición y presencia']},
  {title:'Rosario',src:'assets/comunion-rosario.webp',alt:'Vestido blanco de Primera Comunión con rosario',description:'Mangas de encaje, bordados florales y un rosario que completa el gesto ceremonial.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Símbolo y delicadeza']},
  {title:'Azul Gala',src:'assets/evento-azul-gala.webp',alt:'Vestido azul gala sin tirantes',description:'Escote corazón, pliegues cruzados y una cascada lateral sobre una falda de gran amplitud.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Volumen y elegancia']},
  {title:'Azul Majestad',src:'assets/evento-azul-majestad.webp',alt:'Vestido azul de manga larga',description:'Mangas largas, drapeado lateral y un broche luminoso que define la cintura.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Presencia y estructura']},
  {title:'Azul Clásico',src:'assets/evento-azul-clasico.webp',alt:'Vestido azul clásico sin mangas',description:'Una línea limpia y atemporal con pliegues suaves y un detalle joya lateral.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Sencillez y distinción']},
  {title:'Azul Asimétrico',src:'assets/evento-azul-asimetrico.webp',alt:'Vestido corto azul asimétrico',description:'Una manga, drapeado envolvente y largo corto para una celebración contemporánea.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Asimetría y movimiento']},
  {title:'Rubí',src:'assets/evento-rubi.webp',alt:'Vestido rojo de lentejuelas',description:'Lentejuelas rubí, una manga y abertura frontal para una entrada de alto impacto.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Brillo y carácter']},
  {title:'Noche Azul',src:'assets/evento-noche-azul.webp',alt:'Vestido azul con abertura frontal',description:'Satinado azul profundo, tirantes delicados y una falda abierta de caída fluida.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Fluidez y noche']},
  {title:'Lavanda',src:'assets/evento-lavanda.webp',alt:'Vestido corto lavanda asimétrico',description:'Satinado lavanda, una manga y una cascada lateral de gesto ligero.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Color y frescura']},
  {title:'Rosa Jardín',src:'assets/infantil-rosa-jardin.webp',alt:'Vestido infantil rosa con flores y falda de tul',description:'Flores en relieve, tul luminoso y un lazo lateral para una silueta delicada.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Dulce y ceremonial']},
  {title:'Borgoña Clásico',src:'assets/infantil-borgona.webp',alt:'Vestido formal borgoña de manga larga',description:'Línea larga y depurada en tono borgoña, con mangas y caída elegante.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Sobria y atemporal']},
  {title:'Rosa Sueño',src:'assets/infantil-rosa-sueno.webp',alt:'Vestido infantil rosa de manga larga con lazo y tul',description:'Mangas suaves, lazo central y una falda de tul con destellos discretos.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Suave y encantadora']},
  {title:'Rosa Dalia',src:'assets/infantil-rosa-dalia.webp',alt:'Vestido infantil rosa empolvado de manga larga',description:'Rosa empolvado, volumen ligero y un lazo preciso para celebraciones especiales.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Moderna y delicada']}
];
const categories=pieces.map(p=>{const c=p.details.join(' ');return c.includes('Novias')?'novias':c.includes('XV')?'quince':c.includes('Primera')?'ceremonia':c.includes('Eventos')?'ocasion':'infantiles'});
const viewer=document.querySelector('.viewer');let active=0;
function renderViewer(index){if(!viewer)return;active=(index+pieces.length)%pieces.length;const p=pieces[active];viewer.querySelector('img').src=p.src;viewer.querySelector('img').alt=p.alt;viewer.querySelector('h2').textContent=p.title;viewer.querySelector('.viewer-description').textContent=p.description;viewer.querySelector('.viewer-details').innerHTML=p.details.map(x=>`<li>${x}</li>`).join('');viewer.querySelector('.viewer-count').textContent=`${String(active+1).padStart(2,'0')} / ${String(pieces.length).padStart(2,'0')}`}
function openViewer(index){if(!viewer)return;renderViewer(index);viewer.showModal();document.body.style.overflow='hidden'}
if(viewer){viewer.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.querySelector('.viewer-prev').onclick=()=>renderViewer(active-1);viewer.querySelector('.viewer-next').onclick=()=>renderViewer(active+1);viewer.addEventListener('close',()=>document.body.style.overflow='');viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()})}
const catalog=document.querySelector('#catalog');
if(catalog){catalog.innerHTML=pieces.map((p,i)=>`<button class="catalog-card" data-index="${i}" data-category="${categories[i]}" aria-label="Ampliar ${p.title}"><span class="image"><img src="${p.src}" alt="${p.alt}" width="1024" height="1536" loading="lazy"></span><span class="meta"><span><small>${p.details[1].replace('Colección — ','')}</small><h2>${p.title}</h2></span><span>↗</span></span></button>`).join('');catalog.querySelectorAll('.catalog-card').forEach(c=>c.onclick=()=>openViewer(Number(c.dataset.index)));const requested=new URLSearchParams(location.search).get('categoria');const setFilter=value=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('is-active',b.dataset.filter===value));catalog.querySelectorAll('.catalog-card').forEach(c=>c.hidden=value!=='all'&&c.dataset.category!==value)};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));if(requested&&document.querySelector(`[data-filter="${requested}"]`))setFilter(requested)}
const stage=document.querySelector('#gallery-stage');
if(stage){stage.innerHTML=pieces.map((p,i)=>`<button class="gallery-card" data-index="${i}" data-category="${categories[i]}"><img src="${p.src}" alt="${p.alt}" loading="lazy"><span>${p.details[1].replace('Colección — ','')}<b>${p.title}</b></span></button>`).join('');const cards=[...stage.children],current=document.querySelector('.gallery-current'),totalEl=document.querySelector('.gallery-total');let visible=[...cards],position=0;const render=()=>{const total=visible.length;cards.forEach(card=>{const shown=visible.includes(card);card.hidden=!shown;if(!shown)return;let delta=visible.indexOf(card)-position;if(delta>total/2)delta-=total;if(delta<-total/2)delta+=total;const d=Math.abs(delta);card.style.setProperty('--gx',`${delta*60}%`);card.style.setProperty('--gz',`${-d*210}px`);card.style.setProperty('--gry',`${delta*-18}deg`);card.style.setProperty('--gs',Math.max(.68,1-d*.13));card.style.setProperty('--go',d>2?0:1-d*.2);card.style.zIndex=20-d;card.classList.toggle('center',delta===0);card.tabIndex=d>1?-1:0});current.textContent=String(position+1).padStart(2,'0');totalEl.textContent=String(total).padStart(2,'0')};const move=n=>{position=(position+n+visible.length)%visible.length;render()};document.querySelector('.gallery-arrow.prev').onclick=()=>move(-1);document.querySelector('.gallery-arrow.next').onclick=()=>move(1);cards.forEach(card=>card.onclick=()=>{const i=visible.indexOf(card);if(i===position)openViewer(Number(card.dataset.index));else{position=i;render()}});document.querySelectorAll('[data-gallery-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gallery-filter]').forEach(x=>x.classList.toggle('is-active',x===b));visible=cards.filter(c=>b.dataset.galleryFilter==='all'||c.dataset.category===b.dataset.galleryFilter);position=0;render()});let start=0;stage.onpointerdown=e=>{start=e.clientX;stage.setPointerCapture(e.pointerId)};stage.onpointerup=e=>{if(Math.abs(e.clientX-start)>40)move(e.clientX<start?1:-1)};render()}
const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#nav');if(toggle){toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false')}))}
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&document.querySelector('.home-hero>img'))addEventListener('scroll',()=>document.querySelector('.home-hero>img').style.transform=`translateY(${Math.min(scrollY*.06,45)}px) scale(1.015)`,{passive:true});
