const pieces = [
  {title:'Marfil',src:'assets/novia-encaje.webp',alt:'Vestido de novia satinado de manga larga',description:'Satinado limpio, mangas largas y pliegues diagonales que definen una silueta serena.',details:['Nombre — provisional','Colección — Novias','Lectura — Sastrería y pureza']},
  {title:'Encaje Imperial',src:'assets/novia-satin.webp',alt:'Vestido de novia de manga larga con encaje integral',description:'Escote profundo, encaje floral y una falda amplia que prolonga el detalle hasta la cola.',details:['Nombre — provisional','Colección — Novias','Lectura — Encaje y presencia']},
  {title:'Regencia',src:'assets/novia-sirena.webp',alt:'Vestido de novia de cuello alto y encaje',description:'Cuello alto, manga larga y aplicaciones que equilibran tradición y estructura.',details:['Nombre — provisional','Colección — Novias','Lectura — Clasicismo y detalle']},
  {title:'Aurora',src:'assets/novia-romantica.webp',alt:'Vestido de novia con escote abierto y aplicaciones florales',description:'Un escote abierto enmarcado por flores y una falda luminosa de gran amplitud.',details:['Nombre — provisional','Colección — Novias','Lectura — Romanticismo y volumen']},
  {title:'Azul Medianoche',src:'assets/quince-azul.webp',alt:'Vestido azul medianoche de XV años',description:'Azul profundo, corsetería bordada y destellos que recorren una falda de gran volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Profundidad y brillo']},
  {title:'Verde Salvia',src:'assets/quince-verde.webp',alt:'Vestido verde salvia de XV años',description:'Un verde sereno con aplicaciones florales y transparencias delicadas en el cuerpo.',details:['Nombre — provisional','Colección — XV años','Lectura — Frescura y detalle']},
  {title:'Rosa Nácar',src:'assets/quince-rosa.webp',alt:'Vestido rosa nácar de XV años',description:'Rosa luminoso, cuello bordado y una silueta clásica de presencia suave.',details:['Nombre — provisional','Colección — XV años','Lectura — Romance y luz']},
  {title:'Violeta Imperial',src:'assets/quince-lavanda.webp',alt:'Vestido violeta de XV años',description:'Un violeta sofisticado con cuello transparente y bordados que acentúan el volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Color y textura']},
  {title:'Rosa Corona',src:'assets/quince-rosa-retrato.webp',alt:'Vestido rosa de XV años con modelo y corona',description:'Encaje de manga larga, brillo tenue y una imagen completa de celebración.',details:['Nombre — provisional','Colección — XV años','Lectura — Elegancia ceremonial']},
  {title:'Clásica',src:'assets/ceremonia-clasica.webp',alt:'Vestido blanco infantil de ceremonia',description:'Una pieza blanca de líneas serenas, mangas delicadas y acabado de encaje.',details:['Nombre — provisional','Colección — Ceremonia','Lectura — Delicadeza y tradición']},
  {title:'Caballero',src:'assets/ceremonia-nino.webp',alt:'Traje blanco infantil de ceremonia',description:'Sastrería blanca con detalles formales para una ocasión significativa.',details:['Nombre — provisional','Colección — Ceremonia','Lectura — Sastrería y distinción']},
  {title:'Celebración',src:'assets/ceremonia-nina.webp',alt:'Vestido blanco infantil con falda de volantes',description:'Capas ligeras, lazo frontal y una silueta pensada para moverse con libertad.',details:['Nombre — provisional','Colección — Ceremonia','Lectura — Movimiento y alegría']},
  {title:'Esmeralda',src:'assets/ocasion-esmeralda.webp',alt:'Vestido verde esmeralda de una manga',description:'Un drapeado de una manga y un tono profundo para noches de presencia segura.',details:['Nombre — provisional','Colección — Ocasión','Lectura — Drapeado y color']},
  {title:'Rosa Satin',src:'assets/ocasion-rosa.webp',alt:'Vestido corto rosa satinado',description:'Proporción corta, brillo satinado y una línea femenina de expresión limpia.',details:['Nombre — provisional','Colección — Ocasión','Lectura — Brillo y movimiento']}
];
const viewer=document.querySelector('.viewer'), viewerImg=viewer.querySelector('img'), viewerTitle=viewer.querySelector('h2'), viewerDescription=viewer.querySelector('.viewer-description'), viewerDetails=viewer.querySelector('.viewer-details'), viewerCount=viewer.querySelector('.viewer-count');
let active=0;
function renderViewer(index){active=(index+pieces.length)%pieces.length;const p=pieces[active];viewerImg.src=p.src;viewerImg.alt=p.alt;viewerTitle.textContent=p.title;viewerDescription.textContent=p.description;viewerDetails.innerHTML=p.details.map(x=>`<li>${x}</li>`).join('');viewerCount.textContent=`0${active+1} / 0${pieces.length}`}
function openViewer(index){renderViewer(index);viewer.showModal();document.body.classList.add('is-locked')}
document.querySelectorAll('.art-card').forEach(card=>card.addEventListener('click',()=>openViewer(Number(card.dataset.index))));
document.querySelectorAll('[data-photo-index]').forEach(photo=>photo.addEventListener('click',()=>openViewer(Number(photo.dataset.photoIndex))));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('is-active',b===button));document.querySelectorAll('.art-card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter})}));

const galleryCards=[...document.querySelectorAll('.gallery-3d-card')],galleryStage=document.querySelector('.gallery-3d-stage'),galleryCurrent=document.querySelector('.gallery-current'),galleryTotal=document.querySelector('.gallery-total');let galleryVisible=[...galleryCards],galleryActive=0;
function renderGallery(){const total=galleryVisible.length;galleryCards.forEach(card=>{const visible=galleryVisible.includes(card);card.hidden=!visible;if(!visible)return;const index=galleryVisible.indexOf(card);let delta=index-galleryActive;if(delta>total/2)delta-=total;if(delta<-total/2)delta+=total;const distance=Math.abs(delta);card.style.setProperty('--gx',`${delta*58}%`);card.style.setProperty('--gz',`${-distance*190}px`);card.style.setProperty('--gry',`${delta*-16}deg`);card.style.setProperty('--gscale',String(Math.max(.7,1-distance*.12)));card.style.setProperty('--gopacity',String(distance>2?0:1-distance*.18));card.style.zIndex=String(20-distance);card.classList.toggle('is-center',delta===0);card.tabIndex=distance>1?-1:0});galleryCurrent.textContent=String(galleryActive+1).padStart(2,'0');galleryTotal.textContent=String(total).padStart(2,'0')}
function moveGallery(direction){galleryActive=(galleryActive+direction+galleryVisible.length)%galleryVisible.length;renderGallery()}
document.querySelector('.gallery-arrow--prev').addEventListener('click',()=>moveGallery(-1));document.querySelector('.gallery-arrow--next').addEventListener('click',()=>moveGallery(1));
galleryCards.forEach(card=>card.addEventListener('click',()=>{const index=galleryVisible.indexOf(card);if(index===galleryActive)openViewer(Number(card.dataset.galleryIndex));else{galleryActive=index;renderGallery()}}));
document.querySelectorAll('[data-gallery-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-gallery-filter]').forEach(b=>b.classList.toggle('is-active',b===button));galleryVisible=galleryCards.filter(card=>button.dataset.galleryFilter==='all'||card.dataset.galleryCategory===button.dataset.galleryFilter);galleryActive=0;renderGallery()}));
let galleryStartX=0;galleryStage.addEventListener('pointerdown',e=>{galleryStartX=e.clientX;galleryStage.setPointerCapture(e.pointerId)});galleryStage.addEventListener('pointerup',e=>{const distance=e.clientX-galleryStartX;if(Math.abs(distance)>45)moveGallery(distance<0?1:-1)});renderGallery();
viewer.querySelector('.viewer-close').addEventListener('click',()=>viewer.close());viewer.querySelector('.viewer-prev').addEventListener('click',()=>renderViewer(active-1));viewer.querySelector('.viewer-next').addEventListener('click',()=>renderViewer(active+1));viewer.addEventListener('close',()=>document.body.classList.remove('is-locked'));viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false')}));
document.querySelector('#year').textContent=new Date().getFullYear();
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){window.addEventListener('scroll',()=>{const y=window.scrollY;document.querySelector('.hero-media img').style.transform=`translateY(${Math.min(y*.08,55)}px) scale(1.01)`},{passive:true})}
