const pieces = [
  {title:'Marfil',src:'assets/novia-encaje.webp',alt:'Vestido de novia satinado de manga larga',description:'Satinado limpio, mangas largas y pliegues diagonales que definen una silueta serena.',details:['Nombre — provisional','Colección — Novias','Lectura — Sastrería y pureza']},
  {title:'Encaje Imperial',src:'assets/novia-satin.webp',alt:'Vestido de novia de manga larga con encaje integral',description:'Escote profundo, encaje floral y una falda amplia que prolonga el detalle hasta la cola.',details:['Nombre — provisional','Colección — Novias','Lectura — Encaje y presencia']},
  {title:'Regencia',src:'assets/novia-sirena.webp',alt:'Vestido de novia de cuello alto y encaje',description:'Cuello alto, manga larga y aplicaciones que equilibran tradición y estructura.',details:['Nombre — provisional','Colección — Novias','Lectura — Clasicismo y detalle']},
  {title:'Aurora',src:'assets/novia-romantica.webp',alt:'Vestido de novia con escote abierto y aplicaciones florales',description:'Un escote abierto enmarcado por flores y una falda luminosa de gran amplitud.',details:['Nombre — provisional','Colección — Novias','Lectura — Romanticismo y volumen']},
  {title:'Azul Medianoche',src:'assets/quince-azul.webp',alt:'Vestido azul medianoche de XV años',description:'Azul profundo, corsetería bordada y destellos que recorren una falda de gran volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Profundidad y brillo']},
  {title:'Verde Salvia',src:'assets/quince-verde.webp',alt:'Vestido verde salvia de XV años',description:'Un verde sereno con aplicaciones florales y transparencias delicadas en el cuerpo.',details:['Nombre — provisional','Colección — XV años','Lectura — Frescura y detalle']},
  {title:'Rosa Nácar',src:'assets/quince-rosa.webp',alt:'Vestido rosa nácar de XV años',description:'Rosa luminoso, cuello bordado y una silueta clásica de presencia suave.',details:['Nombre — provisional','Colección — XV años','Lectura — Romance y luz']},
  {title:'Violeta Imperial',src:'assets/quince-lavanda.webp',alt:'Vestido violeta de XV años',description:'Un violeta sofisticado con cuello transparente y bordados que acentúan el volumen.',details:['Nombre — provisional','Colección — XV años','Lectura — Color y textura']},
  {title:'Rosa Corona',src:'assets/quince-rosa-retrato.webp',alt:'Vestido rosa de XV años con modelo y corona',description:'Encaje de manga larga, brillo tenue y una imagen completa de celebración.',details:['Nombre — provisional','Colección — XV años','Lectura — Elegancia ceremonial']},
  {title:'Lirio',src:'assets/comunion-lirio.webp',alt:'Vestido blanco de Primera Comunión con cinturón floral',description:'Mangas delicadas, cinturón satinado y un borde floral que enmarca la falda.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Pureza y detalle']},
  {title:'Gracia',src:'assets/comunion-gracia.webp',alt:'Vestido satinado de Primera Comunión',description:'Satinado limpio, falda plisada y una flor lateral de expresión serena.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Sencillez y luz']},
  {title:'Coral de Luz',src:'assets/comunion-coral.webp',alt:'Vestido blanco de encaje con cinturón coral',description:'Encaje floral y un acento coral que aporta identidad a la silueta clásica.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Encaje y contraste']},
  {title:'Capilla',src:'assets/comunion-capilla.webp',alt:'Vestido blanco de Primera Comunión en una iglesia',description:'Una pieza de encaje suave presentada en la intimidad luminosa de la ceremonia.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Tradición y presencia']},
  {title:'Rosario',src:'assets/comunion-rosario.webp',alt:'Vestido blanco de Primera Comunión con rosario',description:'Mangas de encaje, bordados florales y un rosario que completa el gesto ceremonial.',details:['Nombre — provisional','Colección — Primera Comunión','Lectura — Símbolo y delicadeza']},
  {title:'Azul Gala',src:'assets/evento-azul-gala.webp',alt:'Vestido azul gala sin tirantes',description:'Escote corazón, pliegues cruzados y una cascada lateral sobre una falda de gran amplitud.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Volumen y elegancia']},
  {title:'Azul Majestad',src:'assets/evento-azul-majestad.webp',alt:'Vestido azul de manga larga',description:'Mangas largas, drapeado lateral y un broche luminoso que define la cintura.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Presencia y estructura']},
  {title:'Azul Clásico',src:'assets/evento-azul-clasico.webp',alt:'Vestido azul clásico sin mangas',description:'Una línea limpia y atemporal con pliegues suaves y un detalle joya lateral.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Sencillez y distinción']},
  {title:'Azul Asimétrico',src:'assets/evento-azul-asimetrico.webp',alt:'Vestido corto azul asimétrico',description:'Una manga, drapeado envolvente y largo corto para una celebración contemporánea.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Asimetría y movimiento']},
  {title:'Rubí',src:'assets/evento-rubi.webp',alt:'Vestido rojo de lentejuelas',description:'Lentejuelas rubí, una manga y abertura frontal para una entrada de alto impacto.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Brillo y carácter']},
  {title:'Noche Azul',src:'assets/evento-noche-azul.webp',alt:'Vestido azul con abertura frontal',description:'Satinado azul profundo, tirantes delicados y una falda abierta de caída fluida.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Fluidez y noche']},
  {title:'Lavanda',src:'assets/evento-lavanda.webp',alt:'Vestido corto lavanda asimétrico',description:'Satinado lavanda, una manga y una cascada lateral de gesto ligero.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Color y frescura']},
  {title:'Rosa Jardín',src:'assets/infantil-rosa-jardin.webp',alt:'Vestido infantil rosa con flores y falda de tul',description:'Flores en relieve, tul luminoso y un lazo lateral para una silueta delicada.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Dulce y ceremonial']},
  {title:'Borgoña Clásico',src:'assets/infantil-borgona.webp',alt:'Vestido formal borgoña de manga larga',description:'Línea larga y depurada en tono borgoña, con mangas y caída elegante.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Sobria y atemporal']},
  {title:'Rosa Sueño',src:'assets/infantil-rosa-sueno.webp',alt:'Vestido infantil rosa de manga larga con lazo y tul',description:'Mangas suaves, lazo central y una falda de tul con destellos discretos.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Suave y encantadora']},
  {title:'Rosa Dalia',src:'assets/infantil-rosa-dalia.webp',alt:'Vestido infantil rosa empolvado de manga larga',description:'Rosa empolvado, volumen ligero y un lazo preciso para celebraciones especiales.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Moderna y delicada']},
  {title:'Azul Encaje',src:'assets/nuevo-azul-encaje.webp',alt:'Vestido azul de encaje floral y manga corta',description:'Encaje floral azul, manga corta y falda midi de volumen sereno.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Encaje y delicadeza']},
  {title:'Marfil Noche',src:'assets/nuevo-marfil-corto.webp',alt:'Vestido corto marfil de hombros descubiertos',description:'Una silueta corta con hombros descubiertos y drapeado envolvente.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Limpieza y carácter']},
  {title:'Verde Esmeralda',src:'assets/nuevo-verde-esmeralda.webp',alt:'Vestido largo verde esmeralda cruzado',description:'Satinado verde, escote cruzado y lazo lateral sobre una falda fluida.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Fluidez y presencia']},
  {title:'Azul Brisa',src:'assets/nuevo-azul-brisa.webp',alt:'Vestido largo azul claro con mangas fluidas',description:'Azul claro, mangas ligeras y un delicado acento de brillo en la cintura.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Ligereza y luz']},
  {title:'Celeste Romance',src:'assets/nuevo-azul-celeste.webp',alt:'Vestido largo celeste de mangas abullonadas',description:'Satinado celeste, mangas abullonadas y falda amplia de caída luminosa.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Volumen y suavidad']},
  {title:'Rosa Satén',src:'assets/nuevo-rosa-satin.webp',alt:'Vestido largo rosa satinado de manga larga',description:'Escote cuadrado, mangas largas y satén rosa de brillo delicado.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Color y sencillez']},
  {title:'Lavanda Encaje',src:'assets/nuevo-lavanda-encaje.webp',alt:'Conjunto formal lavanda de encaje',description:'Conjunto de líneas clásicas cubierto por encaje floral en tono lavanda.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Clasicismo y textura']},
  {title:'Rubí Retrato',src:'assets/nuevo-rubi-retrato.webp',alt:'Vestido rojo satinado con abertura y cinturón brillante',description:'Satinado rubí, abertura frontal y un cinturón luminoso que define la cintura.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Movimiento y brillo']},
  {title:'Rubí Gala',src:'assets/nuevo-rubi-gala.webp',alt:'Vestido rojo largo cruzado en una celebración',description:'Escote cruzado, falda abierta y rojo intenso para una celebración especial.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Gala y energía']},
  {title:'Azul Drapeado',src:'assets/nuevo-azul-drapeado.webp',alt:'Vestido azul claro ajustado con drapeado lateral',description:'Silueta alargada en satén azul con drapeado diagonal y mangas escultóricas.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Estructura y satén']},
  {title:'Rosa Plata',src:'assets/nuevo-rosa-plata.webp',alt:'Vestido corto rosa con encaje plateado',description:'Falda de tul rosa y aplicaciones plateadas sobre un cuerpo de manga larga.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Contraste y encaje']},
  {title:'Dúo Encaje',src:'assets/nuevo-duo-encaje.webp',alt:'Dos vestidos formales en verde y rosa con encaje',description:'Dos propuestas de encaje: verde profundo y rosa suave con aplicaciones plateadas.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Versatilidad y detalle']},
  {title:'Dúo Clásico',src:'assets/nuevo-duo-clasico.webp',alt:'Vestidos formales negro y marfil',description:'Dos siluetas midi en negro y marfil con detalles gráficos y mangas definidas.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Contraste y elegancia']},
  {title:'Azul Logro',src:'assets/nuevo-graduacion-azul.webp',alt:'Vestido azul claro usado en una graduación',description:'Una silueta azul satinada acompañando un momento de logro y celebración.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Experiencia real']},
  {title:'Trío Gala',src:'assets/nuevo-trio-gala.webp',alt:'Tres vestidos de gala blanco, lavanda y azul',description:'Tres interpretaciones de gala con contraste gráfico, encaje y satén drapeado.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Variedad y ocasión']},
  {title:'Rosa Metálico',src:'assets/nuevo-rosa-metalico.webp',alt:'Vestido midi rosa metálico cruzado',description:'Brillo rosa suave, escote cruzado y falda midi de pliegues amplios.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Brillo y comodidad']},
  {title:'Cuadros Clásicos',src:'assets/nuevo-cuadros.webp',alt:'Vestido largo de cuadros blanco y negro',description:'Cuadros en blanco y negro, botonadura frontal y una silueta larga estructurada.',details:['Nombre — provisional','Colección — Eventos especiales','Lectura — Gráfico y atemporal']},
  {title:'Lila Floral',src:'assets/nuevo-infantil-lila.webp',alt:'Vestido infantil blanco con flores pequeñas y lazos lilas',description:'Estampado delicado, falda amplia y lazos lilas para una celebración infantil.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Frescura y color']},
  {title:'Dorado Jardín',src:'assets/nuevo-infantil-dorado.webp',alt:'Vestido infantil dorado con flores en relieve',description:'Encaje dorado y flores tridimensionales sobre una falda de volumen festivo.',details:['Nombre — provisional','Colección — Infantiles','Lectura — Textura y celebración']},
  {title:'Dúo Natural',src:'assets/nuevo-duo-casual.webp',alt:'Vestidos casuales blanco y verde con estampado floral',description:'Dos vestidos frescos de líneas amplias, pensados para el movimiento cotidiano.',details:['Nombre — provisional','Colección — Moda casual','Lectura — Frescura y comodidad']},
  {title:'Selección Cotidiana',src:'assets/nuevo-collage-casual.webp',alt:'Selección de seis conjuntos y vestidos casuales',description:'Una muestra de estampados, conjuntos y vestidos ligeros para distintos días.',details:['Nombre — provisional','Colección — Moda casual','Lectura — Variedad y color']},
  {title:'Floral Gris',src:'assets/nuevo-floral-gris.webp',alt:'Vestido largo gris y blanco de estampado floral',description:'Mangas abullonadas y estampado floral gráfico sobre una silueta larga.',details:['Nombre — provisional','Colección — Moda casual','Lectura — Estampado y volumen']},
  {title:'Celeste Drapeado · Retrato',src:'assets/cliente-celeste-largo-retrato.webp',alt:'Clienta de AZ Moda con vestido largo azul celeste drapeado',description:'Una pieza realizada por AZ Moda, fotografiada en movimiento para mostrar su caída y abertura lateral.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Drapeado y movimiento']},
  {title:'Celeste Drapeado · Atelier',src:'assets/cliente-celeste-largo-atelier.webp',alt:'Vestido largo azul celeste drapeado sobre maniquí',description:'Vista completa del diseño, con escote recto, mangas suaves y drapeado que define la silueta.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Silueta completa']},
  {title:'Celeste Drapeado · Exterior',src:'assets/cliente-celeste-largo-exterior.webp',alt:'Clienta con vestido largo azul celeste en un paisaje al atardecer',description:'El diseño terminado en un entorno exterior, donde la luz acompaña el tono celeste y su movimiento.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Experiencia real']},
  {title:'Azul Sereno · Mirador',src:'assets/cliente-celeste-corto-mirador.webp',alt:'Clienta con vestido corto azul celeste en un mirador',description:'Un vestido fresco de manga corta y volumen ligero, creado para acompañar momentos cotidianos.',details:['Trabajo — realizado','Colección — Moda casual','Lectura — Frescura y comodidad']},
  {title:'Azul Sereno · Ciudad',src:'assets/cliente-celeste-corto-ciudad.webp',alt:'Clienta con vestido corto azul celeste en un espacio urbano',description:'La pieza puesta en contexto real, con una silueta cómoda y femenina de movimiento natural.',details:['Trabajo — realizado','Colección — Moda casual','Lectura — Uso real']},
  {title:'Azul Sereno · Atelier',src:'assets/cliente-celeste-corto-atelier.webp',alt:'Vestido corto azul celeste sobre maniquí',description:'Vista del diseño con escote cuadrado, mangas de volumen sutil y cintura definida.',details:['Trabajo — realizado','Colección — Moda casual','Lectura — Detalle y confección']},
  {title:'Camisa Blanca Esencial',src:'assets/esencial-camisa-blanca.webp',alt:'Camisa blanca entallada de manga larga sobre maniquí',description:'Una camisa blanca de línea limpia, cuello definido y silueta entallada para combinar con distintos estilos.',details:['Trabajo — realizado','Colección — Línea Esencial','Lectura — Limpieza y versatilidad']},
  {title:'Camisa Rosa Satinada',src:'assets/esencial-camisa-rosa.webp',alt:'Camisa rosa satinada entallada de manga larga sobre maniquí',description:'Brillo suave, cuello clásico y construcción entallada en una pieza pensada para elevar el vestuario diario.',details:['Trabajo — realizado','Colección — Línea Esencial','Lectura — Brillo y estructura']},
  {title:'Verde Salvia · Retrato',src:'assets/trabajo-verde-salvia-cliente.webp',alt:'Clienta de AZ Moda con vestido verde salvia largo al atardecer',description:'Una creación sobre medida en verde salvia, llevada en un entorno natural que resalta su caída suave.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Experiencia real']},
  {title:'Verde Salvia · Atelier',src:'assets/trabajo-verde-salvia-atelier.webp',alt:'Vestido verde salvia largo sobre maniquí',description:'Vista completa del diseño con escote cuadrado, mangas amplias, cinturón delicado y volante inferior.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Silueta completa']},
  {title:'Verde Salvia · Exterior',src:'assets/trabajo-verde-salvia-exterior.webp',alt:'Clienta con vestido verde salvia largo en un paisaje al atardecer',description:'La prenda terminada en movimiento, acompañada por la luz cálida del atardecer.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Movimiento y ocasión']},
  {title:'Azul Petróleo · Retrato I',src:'assets/trabajo-azul-petroleo-cliente-1.webp',alt:'Clienta de AZ Moda con vestido azul petróleo largo',description:'Diseño largo azul petróleo de línea definida y mangas amplias, creado para una ocasión especial.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Experiencia real']},
  {title:'Azul Petróleo · Atelier',src:'assets/trabajo-azul-petroleo-atelier.webp',alt:'Vestido azul petróleo largo sobre maniquí',description:'Vista de taller que permite apreciar la silueta limpia, el cuello redondo y la amplitud de los puños.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Corte y confección']},
  {title:'Azul Petróleo · Retrato II',src:'assets/trabajo-azul-petroleo-cliente-2.webp',alt:'Clienta con vestido azul petróleo largo al atardecer',description:'Una segunda mirada al diseño terminado, integrado a la luz y al paisaje de la celebración.',details:['Trabajo — realizado','Colección — Eventos especiales','Lectura — Presencia y color']}
];
const categories=pieces.map(p=>{const c=p.details.join(' ');return c.includes('Novias')?'novias':c.includes('XV')?'quince':c.includes('Primera')?'ceremonia':c.includes('Eventos')?'ocasion':c.includes('Línea Esencial')?'esencial':c.includes('Moda casual')?'casual':'infantiles'});
const casualHome=document.querySelector('.category-grid');if(casualHome&&!casualHome.querySelector('[href*="casual"]'))casualHome.insertAdjacentHTML('beforeend','<a href="colecciones.html?categoria=casual"><span>06</span><div><small>Día a día</small><h3>Moda casual</h3></div><b>→</b></a>');
const essentialHome=document.querySelector('.category-grid');if(essentialHome&&!essentialHome.querySelector('[href*="esencial"]'))essentialHome.insertAdjacentHTML('beforeend','<a href="colecciones.html?categoria=esencial"><span>07</span><div><small>Prendas para cada día</small><h3>Línea Esencial</h3></div><b>→</b></a>');
const catalogFilters=document.querySelector('.catalog-section .filters');if(catalogFilters&&!catalogFilters.querySelector('[data-filter="casual"]'))catalogFilters.insertAdjacentHTML('beforeend','<button data-filter="casual">Moda casual</button>');
if(catalogFilters&&!catalogFilters.querySelector('[data-filter="esencial"]'))catalogFilters.insertAdjacentHTML('beforeend','<button data-filter="esencial">Línea Esencial</button>');
const galleryFilters=document.querySelector('.gallery-filters');if(galleryFilters&&!galleryFilters.querySelector('[data-gallery-filter="casual"]'))galleryFilters.insertAdjacentHTML('beforeend','<button data-gallery-filter="casual">Moda casual</button>');
if(galleryFilters&&!galleryFilters.querySelector('[data-gallery-filter="esencial"]'))galleryFilters.insertAdjacentHTML('beforeend','<button data-gallery-filter="esencial">Línea Esencial</button>');
const archiveCount=document.querySelector('.page-head .kicker');if(archiveCount)archiveCount.textContent=`Archivo AZ / ${pieces.length} piezas`;
const viewer=document.querySelector('.viewer');let active=0;
function renderViewer(index){if(!viewer)return;active=(index+pieces.length)%pieces.length;const p=pieces[active];viewer.querySelector('img').src=p.src;viewer.querySelector('img').alt=p.alt;viewer.querySelector('h2').textContent=p.title;viewer.querySelector('.viewer-description').textContent=p.description;viewer.querySelector('.viewer-details').innerHTML=p.details.map(x=>`<li>${x}</li>`).join('');viewer.querySelector('.viewer-count').textContent=`${String(active+1).padStart(2,'0')} / ${String(pieces.length).padStart(2,'0')}`}
function openViewer(index){if(!viewer)return;renderViewer(index);viewer.showModal();document.body.style.overflow='hidden'}
if(viewer){viewer.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.querySelector('.viewer-prev').onclick=()=>renderViewer(active-1);viewer.querySelector('.viewer-next').onclick=()=>renderViewer(active+1);viewer.addEventListener('close',()=>document.body.style.overflow='');viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()})}
const catalog=document.querySelector('#catalog');
if(catalog){catalog.innerHTML=pieces.map((p,i)=>`<button class="catalog-card" data-index="${i}" data-category="${categories[i]}" aria-label="Ampliar ${p.title}"><span class="image"><img src="${p.src}" alt="${p.alt}" width="1024" height="1536" loading="lazy"></span><span class="meta"><span><small>${p.details[1].replace('Colección — ','')}</small><h2>${p.title}</h2></span><span>↗</span></span></button>`).join('');catalog.querySelectorAll('.catalog-card').forEach(c=>c.onclick=()=>openViewer(Number(c.dataset.index)));const requested=new URLSearchParams(location.search).get('categoria');const setFilter=value=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('is-active',b.dataset.filter===value));catalog.querySelectorAll('.catalog-card').forEach(c=>c.hidden=value!=='all'&&c.dataset.category!==value)};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));if(requested&&document.querySelector(`[data-filter="${requested}"]`))setFilter(requested)}
const stage=document.querySelector('#gallery-stage');
if(stage){stage.innerHTML=pieces.map((p,i)=>`<button class="gallery-card" data-index="${i}" data-category="${categories[i]}"><img src="${p.src}" alt="${p.alt}" width="768" height="1024" loading="lazy" decoding="async"><span>${p.details[1].replace('Colección — ','')}<b>${p.title}</b></span></button>`).join('');const cards=[...stage.children],current=document.querySelector('.gallery-current'),totalEl=document.querySelector('.gallery-total');let visible=[...cards],position=0;const render=()=>{const total=visible.length;cards.forEach(card=>{const shown=visible.includes(card);card.hidden=!shown;if(!shown)return;let delta=visible.indexOf(card)-position;if(delta>total/2)delta-=total;if(delta<-total/2)delta+=total;const d=Math.abs(delta);card.style.setProperty('--gx',`${delta*104}%`);card.style.setProperty('--gs',d===0?1:.9);card.style.setProperty('--go',d>1?0:.48);card.style.zIndex=20-d;card.classList.toggle('center',delta===0);card.tabIndex=d>1?-1:0;card.setAttribute('aria-hidden',String(d>1))});current.textContent=String(position+1).padStart(2,'0');totalEl.textContent=String(total).padStart(2,'0')};const move=n=>{if(!visible.length)return;position=(position+n+visible.length)%visible.length;render()};document.querySelector('.gallery-arrow.prev').onclick=()=>move(-1);document.querySelector('.gallery-arrow.next').onclick=()=>move(1);cards.forEach(card=>card.onclick=()=>{const i=visible.indexOf(card);if(i===position)openViewer(Number(card.dataset.index));else{position=i;render()}});document.querySelectorAll('[data-gallery-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gallery-filter]').forEach(x=>x.classList.toggle('is-active',x===b));visible=cards.filter(c=>b.dataset.galleryFilter==='all'||c.dataset.category===b.dataset.galleryFilter);position=0;render()});let start=0;stage.onpointerdown=e=>{start=e.clientX;stage.setPointerCapture(e.pointerId)};stage.onpointerup=e=>{if(Math.abs(e.clientX-start)>40)move(e.clientX<start?1:-1)};render()}
const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#nav');if(nav&&!nav.querySelector('[href="resenas.html"]')){const link=document.createElement('a');link.href='resenas.html';link.textContent='Opiniones';nav.insertBefore(link,nav.querySelector('.nav-contact'))}if(toggle){toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false')}))}
const footer=document.querySelector('footer');if(footer&&!footer.querySelector('.social-links')){const socials=document.createElement('div');socials.className='social-links';socials.setAttribute('aria-label','Redes sociales');socials.innerHTML='<a href="https://www.instagram.com/azmoda_colombia/" target="_blank" rel="noopener" aria-label="Instagram de AZ Moda">Instagram <span>↗</span></a><a href="https://www.facebook.com/AZMODACOLOMBIA/" target="_blank" rel="noopener" aria-label="Facebook de AZ Moda">Facebook <span>↗</span></a>';footer.insertBefore(socials,footer.querySelector('small'))}
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&document.querySelector('.home-hero>img'))addEventListener('scroll',()=>document.querySelector('.home-hero>img').style.transform=`translateY(${Math.min(scrollY*.06,45)}px) scale(1.015)`,{passive:true});
