const SUPABASE_URL='https://woohfmqgtvbznqjssgno.supabase.co';
const SUPABASE_KEY='sb_publishable_1q03w-BKHED-9bGWeGaA3w_FnVwMQo4';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const form=document.querySelector('#review-form'),photos=document.querySelector('#review-photos'),preview=document.querySelector('#photo-preview'),statusEl=document.querySelector('#form-status'),submit=document.querySelector('.submit-review'),comment=document.querySelector('#review-comment');
if(form){
const categorySelect=document.querySelector('#review-category');if(categorySelect&&!categorySelect.querySelector('[value="Moda casual"]'))categorySelect.insertAdjacentHTML('beforeend','<option>Moda casual</option>');if(categorySelect&&!categorySelect.querySelector('[value="Línea Esencial"]'))categorySelect.insertAdjacentHTML('beforeend','<option>Línea Esencial</option>');
comment.addEventListener('input',()=>document.querySelector('#comment-count').textContent=comment.value.length);
photos.addEventListener('change',()=>{const files=[...photos.files];preview.innerHTML='';if(files.length>2){photos.value='';statusEl.textContent='Puedes seleccionar máximo dos fotografías.';return}for(const file of files){if(file.size>6291456){photos.value='';preview.innerHTML='';statusEl.textContent='Cada fotografía debe pesar máximo 6 MB.';return}const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt='Vista previa de la fotografía';preview.append(img)}statusEl.textContent=''});
async function uploadPhoto(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`publicadas/${crypto.randomUUID()}.${ext}`;const response=await fetch(`${SUPABASE_URL}/storage/v1/object/resenas/${path}`,{method:'POST',headers:{...headers,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok)throw new Error('No se pudo subir una fotografía.');return `${SUPABASE_URL}/storage/v1/object/public/resenas/${path}`}
form.addEventListener('submit',async event=>{event.preventDefault();if(form.elements.website.value)return;const selected=[...photos.files];if(selected.length>2)return;submit.disabled=true;statusEl.className='form-status';statusEl.textContent=selected.length?'Subiendo fotografías…':'Publicando tu opinión…';try{const urls=[];for(const file of selected)urls.push(await uploadPhoto(file));const data=new FormData(form);const payload={nombre:String(data.get('nombre')).trim(),calificacion:Number(data.get('calificacion')),comentario:String(data.get('comentario')).trim(),categoria:String(data.get('categoria')),fotos:urls,aprobada:true};const response=await fetch(`${SUPABASE_URL}/rest/v1/resenas`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('No se pudo guardar la opinión.');form.reset();preview.innerHTML='';document.querySelector('#comment-count').textContent='0';statusEl.classList.add('success');statusEl.textContent='¡Gracias! Tu opinión ya está publicada.';await loadReviews()}catch(error){statusEl.classList.add('error');statusEl.textContent=`${error.message} Inténtalo nuevamente.`}finally{submit.disabled=false}});
}
function safe(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
async function loadReviews(){const list=document.querySelector('#reviews-list');if(!list)return;try{const response=await fetch(`${SUPABASE_URL}/rest/v1/resenas?select=*&aprobada=eq.true&order=created_at.desc&limit=30`,{headers,cache:'no-store'});if(!response.ok)throw new Error();const reviews=await response.json();if(!reviews.length){list.innerHTML='<p class="reviews-empty compact">Muy pronto compartiremos las experiencias de quienes han confiado en nuestro trabajo.</p>';return}list.innerHTML=reviews.map(r=>{const hasPhotos=Array.isArray(r.fotos)&&r.fotos.length>0,reviewText=String(r.comentario||''),reply=String(r.respuesta_az||r.respuesta||''),date=r.created_at?new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(r.created_at)):'';return `<article class="review-card ${hasPhotos?'has-photos':'no-photo'}">${hasPhotos?`<div class="review-photos" aria-label="Fotos compartidas por ${safe(r.nombre)}">${r.fotos.slice(0,2).map((url,i)=>`<img src="${safe(url)}" alt="Fotografía ${i+1} compartida por ${safe(r.nombre)}" loading="lazy" width="900" height="1200">`).join('')}</div>`:''}<div class="review-body"><div class="review-stars" aria-label="${r.calificacion} de 5 estrellas">${'★'.repeat(r.calificacion)}${'☆'.repeat(5-r.calificacion)}</div><blockquote class="review-comment"><span>“${safe(reviewText)}”</span></blockquote>${reviewText.length>145?'<button class="review-more" type="button" aria-expanded="false">Leer más <span aria-hidden="true">＋</span></button>':''}<p><strong>${safe(r.nombre)}</strong><span>${safe(r.categoria||'Experiencia AZ')}</span>${date?`<time datetime="${safe(r.created_at)}">${safe(date)}</time>`:''}</p>${reply?`<div class="review-response"><strong>Respuesta de AZ MODA</strong><p>${safe(reply)}</p></div>`:''}</div></article>`}).join('');list.querySelectorAll('.review-more').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.review-card'),expanded=card.classList.toggle('is-expanded');button.setAttribute('aria-expanded',String(expanded));button.childNodes[0].textContent=expanded?'Leer menos ':'Leer más ';button.querySelector('span').textContent=expanded?'−':'＋'}))}catch{list.innerHTML='<p class="reviews-empty compact">No pudimos cargar las opiniones en este momento. Inténtalo nuevamente más tarde.</p>'}}
loadReviews();
