const SUPABASE_URL='https://woohfmqgtvbznqjssgno.supabase.co';
const SUPABASE_KEY='sb_publishable_1q03w-BKHED-9bGWeGaA3w_FnVwMQo4';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const form=document.querySelector('#review-form'),photos=document.querySelector('#review-photos'),preview=document.querySelector('#photo-preview'),statusEl=document.querySelector('#form-status'),submit=document.querySelector('.submit-review'),comment=document.querySelector('#review-comment');
if(form){
comment.addEventListener('input',()=>document.querySelector('#comment-count').textContent=comment.value.length);
photos.addEventListener('change',()=>{const files=[...photos.files];preview.innerHTML='';if(files.length>2){photos.value='';statusEl.textContent='Puedes seleccionar máximo dos fotografías.';return}for(const file of files){if(file.size>6291456){photos.value='';preview.innerHTML='';statusEl.textContent='Cada fotografía debe pesar máximo 6 MB.';return}const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt='Vista previa de la fotografía';preview.append(img)}statusEl.textContent=''});
async function uploadPhoto(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`pendientes/${crypto.randomUUID()}.${ext}`;const response=await fetch(`${SUPABASE_URL}/storage/v1/object/resenas/${path}`,{method:'POST',headers:{...headers,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok)throw new Error('No se pudo subir una fotografía.');return `${SUPABASE_URL}/storage/v1/object/public/resenas/${path}`}
form.addEventListener('submit',async event=>{event.preventDefault();if(form.elements.website.value)return;const selected=[...photos.files];if(selected.length>2)return;submit.disabled=true;statusEl.className='form-status';statusEl.textContent=selected.length?'Subiendo fotografías…':'Enviando tu opinión…';try{const urls=[];for(const file of selected)urls.push(await uploadPhoto(file));const data=new FormData(form);const payload={nombre:String(data.get('nombre')).trim(),calificacion:Number(data.get('calificacion')),comentario:String(data.get('comentario')).trim(),categoria:String(data.get('categoria')),fotos:urls,aprobada:false};const response=await fetch(`${SUPABASE_URL}/rest/v1/resenas`,{method:'POST',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('No se pudo guardar la opinión.');form.reset();preview.innerHTML='';document.querySelector('#comment-count').textContent='0';statusEl.classList.add('success');statusEl.textContent='¡Gracias! Tu opinión fue recibida y aparecerá cuando AZ Moda la apruebe.'}catch(error){statusEl.classList.add('error');statusEl.textContent=`${error.message} Inténtalo nuevamente.`}finally{submit.disabled=false}});
}
function safe(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
async function loadReviews(){const list=document.querySelector('#reviews-list');if(!list)return;try{const response=await fetch(`${SUPABASE_URL}/rest/v1/resenas?select=id,nombre,calificacion,comentario,categoria,fotos,created_at&aprobada=eq.true&order=created_at.desc&limit=30`,{headers});if(!response.ok)throw new Error();const reviews=await response.json();if(!reviews.length){list.innerHTML='<div class="reviews-empty"><h3>Aún no hay opiniones publicadas.</h3><p>Cuando AZ Moda apruebe las primeras reseñas, aquí aparecerán sus estrellas, comentarios y fotografías.</p><a href="resenas.html">Compartir una experiencia →</a></div>';return}list.innerHTML=reviews.map(r=>`<article class="review-card">${r.fotos?.length?`<div class="review-photos">${r.fotos.slice(0,2).map((url,i)=>`<img src="${safe(url)}" alt="Fotografía ${i+1} compartida por ${safe(r.nombre)}" loading="lazy">`).join('')}</div>`:''}<div class="review-body"><div class="review-stars" aria-label="${r.calificacion} de 5 estrellas">${'★'.repeat(r.calificacion)}${'☆'.repeat(5-r.calificacion)}</div><blockquote>“${safe(r.comentario)}”</blockquote><p><strong>${safe(r.nombre)}</strong><span>${safe(r.categoria||'Experiencia AZ')}</span></p></div></article>`).join('')}catch{list.innerHTML='<div class="reviews-empty"><h3>No pudimos cargar las opiniones.</h3><p>Inténtalo nuevamente en unos minutos.</p></div>'}}
loadReviews();
